name: Download PDFs using RSelenium

on:
  workflow_dispatch:

jobs:
  download-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: rocker/r-ver@v4.0
        with:
          r-version: '4.0.0'

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            docker.io \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev
          R -e "install.packages('RSelenium')"
          R -e "install.packages('dplyr')"

      - name: Run Selenium Docker Container
        run: |
          # Start Docker container with Selenium and Chrome
          sudo docker run -d -p 4444:4444 -v ${{ github.workspace }}/pdfs:/home/selenium/pdfs selenium/standalone-chrome:latest
          
      - name: Run R script to download PDFs
        run: |
          Rscript download_pdfs.R

      - name: List downloaded PDFs
        run: |
          ls -l ${{ github.workspace }}/pdfs

      - name: Commit and push PDFs to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pdfs/*'
          message: 'Add downloaded PDFs'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
