name: Download PDFs with RSelenium

on:
  workflow_dispatch: 

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  download-pdfs:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up R
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # Step 3: Install necessary R libraries
    - name: Install R dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
        Rscript -e "install.packages(c('RSelenium', 'dplyr'))"

    # Step 4: Install Docker and Chrome (for Selenium)
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl enable --now docker

    # Step 5: Run RSelenium to download PDFs
    - name: Run RSelenium to download PDFs
      run: |
        # Start Docker container with Selenium and Chrome
        sudo docker run -d -p 4444:4444 selenium/standalone-chrome:latest

        # Run the R script to download PDFs (ensure the script is named `download_pdfs.R`)
        Rscript download_pdfs.R

        # Stop the Selenium container
        sudo docker stop $(sudo docker ps -q --filter ancestor=selenium/standalone-chrome)

    # Step 6: Commit the downloaded PDFs to the repository
    - name: Commit and push downloaded PDFs
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add pdfs/
        git commit -m "Add downloaded PDFs"
        git push
